# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W3nF3cHt83Vv_xLLb_shvD60az6hUKY6
"""

print ("Bienvenido a mi trivia sobre computación")
print ("Pondremos a prueba tus conocimientos")


nombre = input("Ingresa tu nombre: ")

# Es importante dar instrucciones sobre cómo jugar:
# Ahora, lo personalizaremos con el nombre del jugador, diciéndole a print() que muestre el contenido de la variable "nombre". Cada cosa distinta que queremos que muestre en la pantalla, la separamos con comas
print("\n Hola", nombre, "responde las siguientes preguntas escribiendo la letra de la alternativa y presionando 'Enter' para enviar tu respuesta:\n")

# OJO, el \n al final de la línea 6 es para dar un "salto de línea"

# Pregunta 1
print ("1) ¿Cómo me llamo?")
print ("a) Fernando")
print ("b) Lucho")
print ("c) Federico")
print ("d) Sergio")

# Almacenamos la respuesta del usuario en la variable "respuesta_1"
respuesta_1 = input("\nTu respuesta: ")

while respuesta_1 !="d":  
  while respuesta_1 not in ("a", "b", "c", "d"):
    respuesta_1 = input("Debes responder a, b, c o d. Ingresa nuevamente tu respuesta: ")
  if respuesta_1 == "a":
    print("Incorrecto!", nombre, "Fernando, ¿en serio?")
  elif respuesta_1 == "b":
    print("Incorrecto!", nombre, "Lucho es un nombre raro")
  elif respuesta_1 == "c":
    print("Incorrecto!", nombre, "Que pereza llamarse Federico")
  else:
    print("Me alegra que sepas mi nombre", nombre, "!")
  respuesta_1 = input("Debes responder a, b, c o d. Ingresa nuevamente tu respuesta: ")
  
# Pregunta 2
print ("1) ¿Cuantos años tengo?")
print ("a) 17")
print ("b) 15")
print ("c) 14")
print ("d) 16")

respuesta_2 = input("\nTu respuesta: ")

while respuesta_2 !="d":  
  while respuesta_2 not in ("a", "b", "c", "d"):
    respuesta_2 = input("Debes responder a, b, c o d. Ingresa nuevamente tu respuesta: ")
  if respuesta_2 == "a":
    print("Incorrecto!", nombre, "No soy tan viejo >:V")
  elif respuesta_2 == "b":
    print("Incorrecto!", nombre, "Soy más maduro que eso")
  elif respuesta_2 == "c":
    print("Incorrecto!", nombre, "¿Tan pequeño me veo?")
  else:
    print("Esa es B)", nombre, "!")
  respuesta_2 = input("Debes responder a, b, c o d. Ingresa nuevamente tu respuesta: ")

# Pregunta 3
print ("1) ¿Cuantas horas duermo al día?")
print ("a) 10")
print ("b) 9")
print ("c) 7")
print ("d) 8")

respuesta_3 = input("\nTu respuesta: ")

while respuesta_3 !="d":  
  while respuesta_3 not in ("a", "b", "c", "d"):
    respuesta_3 = input("Debes responder a, b, c o d. Ingresa nuevamente tu respuesta: ") 
  if respuesta_3 == "a":
    print("Incorrecto!", nombre, "No soy tan dormilon hermano")
  elif respuesta_3 == "b":
    print("Incorrecto!", nombre, "YA QUISIERA")
  elif respuesta_3 == "c":
    print("Incorrecto!", nombre, "Es poco para mi")
  else:
    print("Exacto", nombre, "!")
  respuesta_3 = input("Debes responder a, b, c o d. Ingresa nuevamente tu respuesta: ")



